In [1]:
import pandas as pd
import numpy as np
data= pd.read_json("C:\\Users\\Nazir Kheruwala\\Downloads\\Amazon.json")
data

_id      reviewerID        asin  \
0      {'$oid': '5a13242d741a2384e88f3c11'}  A2WNBOD3WNDNKT  0439886341   
1      {'$oid': '5a13242d741a2384e88f3c0f'}   AKM1MP6P0OYPR  0132793040   
2      {'$oid': '5a13242d741a2384e88f3c12'}  A2CX7LUOHB2NDG  0321732944   
3      {'$oid': '5a13242d741a2384e88f3c10'}  A2NWSAGRHCP8N5  0439886341   
4      {'$oid': '5a13242d741a2384e88f3c13'}  A1GI0U4ZRJA8WN  0439886341   
...                                     ...             ...         ...   
26511  {'$oid': '5a13242d741a2384e88f4735'}  A3JZLSI0HSOUV1  140053271X   
26512               {'$oid': 'fakeid03763'}       USER03763     ASIN063   
26513               {'$oid': 'fakeid03948'}       USER03948     ASIN048   
26514  {'$oid': '5a13242d741a2384e88f4fd5'}   AM64W98FUVRG1  9625993428   
26515  {'$oid': '5a13242d741a2384e88f5d56'}  A38ZYS9AET67X4  B00000G20L   

               reviewerName helpful  \
0                       JAL  [1, 1]   
1      Vicki Gibson "momo4"  [1, 1]   
2                    Bernie  [0, 0]   
3               bowmans2007  [1, 1]   
4                 Truthfull  [4, 4]   
...                     ...     ...   
26511                   Sam  [0, 1]   
26512              User3763  [1, 1]   
26513              User3948  [2, 2]   
26514       ashwaq alsharif  [0, 0]   
26515            ann panero  [0, 0]   

                                              reviewText  overall  \
0      Some of the functions did not work properly.  ...        3   
1      Corey Barker does a great job of explaining Bl...        5   
2      While many beginner DVDs try to teach you ever...        5   
3      It never worked. My daughter worked to earn th...        1   
4      Do not waste your money on this thing it is te...        1   
...                                                  ...      ...   
26511  Device froze on start page and is now unusable...        1   
26512                Would not recommend this to anyone.        1   
26513                Extremely poor quality, do not buy.        1   
26514  it is use less I order it because the mic does...        1   
26515  when I put the film in, it went to &#34;H&#34;...        3   

                                                 summary  unixReviewTime  \
0                                          Disappointing      1374451200   
1                                          Very thorough      1365811200   
2      Adobe Photoshop CS5 Crash Course with master P...      1341100800   
3                                    absolutely horrible      1367193600   
4                         TERRIBLE DONT WASTE YOUR MONEY      1334707200   
...                                                  ...             ...   
26511                              I would not purchase.      1382745600   
26512                                      Not satisfied      1326240000   
26513                                      Not satisfied      1397260800   
26514            don not by fake things it does not work      1388880000   
26515                                             camera      1392595200   

        reviewTime     category  class  
0      07 22, 2013  Electronics      0  
1      04 13, 2013  Electronics      1  
2       07 1, 2012  Electronics      1  
3      04 29, 2013  Electronics      0  
4      04 18, 2012  Electronics      0  
...            ...          ...    ...  
26511  10 26, 2013  Electronics      0  
26512  01 11, 2012  Electronics      0  
26513  04 12, 2014  Electronics      0  
26514   01 5, 2014  Electronics      0  
26515  02 17, 2014  Electronics      0  

[26516 rows x 12 columns]

In [2]:
import tensorflow as tf

In [3]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense


In [4]:
voc_size=5000


In [5]:
X=data.drop('class',axis=1)
y=data['class']
X.shape

(26516, 11)

In [6]:
messages=X.copy()


In [7]:
messages['reviewText'][::]

0        Some of the functions did not work properly.  ...
1        Corey Barker does a great job of explaining Bl...
2        While many beginner DVDs try to teach you ever...
3        It never worked. My daughter worked to earn th...
4        Do not waste your money on this thing it is te...
                               ...                        
26511    Device froze on start page and is now unusable...
26512                  Would not recommend this to anyone.
26513                  Extremely poor quality, do not buy.
26514    it is use less I order it because the mic does...
26515    when I put the film in, it went to &#34;H&#34;...
Name: reviewText, Length: 26516, dtype: object

In [8]:
messages.reset_index(inplace=True)

In [9]:
import nltk
import re
from nltk.corpus import stopwords

In [10]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['reviewText'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [11]:
corpus

['function work properli daughter bought money disappoint function advertis',
 'corey barker great job explain blend mode dvd kelbi train video great pricey buy individu realli want bang buck subscrib kelbi train onlin',
 'mani beginn dvd tri teach everyth know photoshop cs introductori cours show critic thing need know start feel confid photoshop skill bestsel author photoshop trainer matt kloskowski show exactli need know tool filter adjust palett menu item hit ground run photoshop includ layer key master photoshop select essenti tool realli need worri get start camera raw retouch tool find help done dvd solid grasp import featur next level time',
 'never work daughter work earn money get never work buy new one replac',
 'wast money thing terribl boutght product son put phone number rememb date would alway reset would anyth get frustrat threw away absolut spend money',
 'unit work like tec unit better like would buy anoth need ok',
 'exact duplic time warner remot bought wife could c

In [12]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]

In [13]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 3086 4087 1176]
 [3040 2930 3047 ... 3658  672 4076]
 [ 803 4418  584 ... 3758 3007 2372]
 ...
 [   0    0    0 ... 1731 1223 4454]
 [   0    0    0 ...  561 1174 1690]
 [   0    0    0 ... 2509 3188 4233]]


In [14]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       4087, 1690, 3276, 4406, 1135, 1200, 3086, 4087, 1176], dtype=int32)

In [15]:
embedding_vector_features = 40

model = Sequential()
model.add(Input(shape=(sent_length,)))  # ✅ Added input shape explicitly
model.add(Embedding(voc_size, embedding_vector_features))  # ✅ Removed deprecated input_length
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())


NameError: name 'Input' is not defined

In [ ]:
len(embedded_docs),y.shape

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

In [ ]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
y_pred = np.round(model.predict(X_test))

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred)

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


tokenizer = Tokenizer(num_words=voc_size)
tokenizer.fit_on_texts(corpus)

comment = input("Enter your comment: ")

comment = re.sub('[^a-zA-Z]', ' ', comment)
comment = comment.lower()
comment = comment.split()
comment = [ps.stem(word) for word in comment if not word in stopwords.words('english')]
comment = ' '.join(comment)

# Convert the comment to a sequence of integers
comment_sequence = tokenizer.texts_to_sequences([comment])
padded_input = pad_sequences(comment_sequence, padding='pre', maxlen=sent_length)

# Use the trained model to predict if the comment is spam or not
prediction = model.predict(padded_input)
if prediction > 0.5:
    print("The comment is spam.")
else:
    print("The comment is not spam.")


In [ ]:
model.save("nazir.keras")

In [ ]:
# Save the trained model
model.save("oxymoron_model.keras")

# Load the saved model later
from tensorflow.keras.models import load_model

loaded_model = load_model("oxymoron_model.keras")
